services:
  urlshortener:
    image: urlshortener:latest
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    ports:
      - "8080:8080"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure