springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
spring:
  application:
    name: url-shortener
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}